name: Code Quality Checks

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters and static analyzers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit (modified files only)
        run: |
          pre-commit run --from-ref origin/main --to-ref HEAD --all-files
